### ISSUE TITLE
Lightweight tests

### ISSUE THREAD

**Issue by kerscher** [fpco/terraform-aws-foundation#103]
Currently this repository has modules under `examples` that when executed will verify against AWS if modules are correct. This is the most robust and correct way to handle testing. But it suffers from a few problems:

- Running it entails costs
- If `examples` don’t cover all `modules`, then coverage is less than 100%

I propose adding a minimal test environment that can check the code _without_ running a `plan` or `apply`, by executing _at least and for every commit_:

1. `terraform init` for _all_ modules
1. `tflint`
1. checking undeclared variable types
1. checking for inline values

## `terraform init`
The easiest way to do this is to create a `tests/main.tf` file that calls every single module once, with all parameters filled with the default for each type. That means an empty string for strings; empty list for lists; and empty map for maps. `terraform init` surprisingly doesn’t care about this. It works. The same module is used for all next steps.

## `tflint`
Running against the `init`ed `tests/main.tf` finds problematic code as soon as it’s added. In my opinion we should treat `NOTICE` as OK to pass, but anything `WARNING` and above as a failed build.

## Undeclared variable types
This checks if all variables have a type at declaration site. The following is an example of a valid snippet:

```
variable "foo" {
  type        = "string"
  description = "bar"
  default     = "baz"
}
```

Omitting `type = "string"` is a test error. This guarantees that type errors are identical at every call site, as undeclared types will only be resolved at the callee, leading to potentially two modules resolving to different types. This also means that even though `default = []` will infer `type = "list"`, without adding it you will only find breakage if changing to another type once you use the changed variable at the call site.

I have started patching [`terraform-index`](github.com/kerscher/terraform-index) such that variables return their types instead of only their names. When a type hasn’t been explicitly set, it will list it as `undeclared`. Any `undeclared` should trigger a build error. This uses the `hcl` library used by `terraform` itself.

Once there are no more `undeclared`, I can use the patched `terraform-index` to auto-generate the `tests/main.tf` by using default values for every type and the list of variables for each module. The commit would be trivial.

## Inline
Inline values prevent templates from being checked as individual files externally, but this is only a nuisance. The real danger is that forgetting to close an inline delimiter changes semantics of the entire `.tf` file. Check the example below:

```
module "a" {
  source = "some-path"
  param = <<EOF
bar
EOT
}

module "b" {
  source = "some-path"
  param = <<EOF
baz
EOF
}
```

The following code above will `terraform apply` correctly, but `module.a.param` will not be `bar`, and `module.b` will never be created. In modules with nested resources or a large amount of modules this can easily pass unnoticed — specially common since `module`s take no `count`.

A counter-argument is that syntax highlight could potentially showcase this problem. But this cannot be checked without human intervention, as a checker cannot know if `module.b` should or not be created.

# Implementing

Adding under `scripts/ci/*.sh` tests that call each of the things above. Once an image has been created with the dependencies in the tests, we can add it to Travis and add a badge with build status. This last step is by far the easiest part.

**Comment by ketzacoatl** [comment]
This is really great, I love what you have done here. I don't have much feedback to add, but I'll drop it in the PR anyway.

**Comment by kerscher** [comment]
@NorfairKing I would love to hear your thoughts on making these tests robust. Initially I added shell scripts, but converting to Haskell program(s) should be relatively easy.

But I could not think of a way to express invariants that [`validity`](github.com/NorfairKing/validity) would accept :grinning:.

**Comment by NorfairKing** [comment]
> @NorfairKing I would love to hear your thoughts on making these tests robust. 

I'm very glad you asked!

> Initially I added shell scripts, but converting to Haskell program(s) should be relatively easy.

Funnily enough, that's actualy the only review comment I gave on the PR, and I read the PR before I read your question here.
I'm more opposed to bash than I am in favour of Haskell in this case, and the only cheap way I can think of making these robust involves two things:

- An idiot-proof guide to running the tests manually.
- Running the tests on CI.

I would love it if we could have more comprehensive tests on CI, but that would be rather expensive, so I would make those manually trigered, but I guess that's a seperate issue.
