### ISSUE TITLE
Automate lightweight tests

### ISSUE THREAD

**Issue by kerscher** [fpco/terraform-aws-foundation#104]
Provide CI automated capabilites to the tests introduced in #103.

# Requirements

- Docker image with `rg`, `tflint`, `terraform`, `terraform-index` and other needed tools
- `.travis.yml` or other CI build pipeline spec, running the scripts in order:
  1. `tfinit`
  1. `tflint`
  1. `undeclared-variables`
  1. `textual-search`

**Comment by ketzacoatl** [comment]
@kerscher, is there a reason we should run on travis and not gitlab?

**Comment by kerscher** [comment]
Not in my opinion, no. We have talked elsewhere about this, but here are the tradeoffs:

# Travis
- Has a hard limit on timeouts
- Provides public badge

# Gitlab
- Integrated with rest of our tools
- No public badge — but could be added?
- Easier to add “deep” tests with AWS APIs later due to secrets management
