### ISSUE TITLE
`tflint` does not pass

### ISSUE THREAD

**Issue by kerscher** [fpco/terraform-aws-foundation#107]
The following notices and warnings show up against current `master` by `tflint` when ran against `tests/main.tf` (#103) for all modules:

```
../modules/bind-server/main.tf
	NOTICE:63 "iam_instance_profile" is not specified. If you want to change it, you need to recreate the instance. (aws_instance_not_specified_iam_profile)
../modules/dnsmasq-server/main.tf
	NOTICE:62 "iam_instance_profile" is not specified. If you want to change it, you need to recreate the instance. (aws_instance_not_specified_iam_profile)
../modules/vpn-gateway/main.tf
	NOTICE:29 "iam_instance_profile" is not specified. If you want to change it, you need to recreate the instance. (aws_instance_not_specified_iam_profile)
main.tf
	WARNING:348 Module source "../modules/init-snippet-gitlab-docker" is not pinned (terraform_module_pinned_source)

Result: 4 issues  (0 errors , 1 warnings , 3 notices)
```

In my opinion we should fix _at least_ the `WARNING`.

**Comment by ketzacoatl** [comment]
The `init-snippet-gitlab-docker` issue is referring to this code https://github.com/fpco/terraform-aws-foundation/blob/v0.7.2/tests/main.tf#L347-L351

Reading up on `tflint` docs on the topic - https://github.com/wata727/tflint/blob/master/docs/terraform_module_pinned_source.md - I am confused.. this should only happen with modules sourced from git/mercurial, and we're not doing that here. The error even shows the path (on the filesystem) to the module, and the `source` line noted above uses the correct path to reference the module source. I don't see why pinning is an issue here.

Reviewing the module, I also don't see any other issues.. the variables not provided all have defaults, and I don't see why `tflint` is erroring out here.

**Comment by lpaulmp** [comment]
@kerscher this could be a bug in the linter because when I did debug this I got became to the same conclusion that no git or hg in use in this module.

**Comment by ketzacoatl** [comment]
The bug is in https://github.com/wata727/tflint/blob/v0.5.4/detector/terraform_module_pinned_source.go#L25-L37, the regex is not smart enough. I filed https://github.com/wata727/tflint/issues/193 with upstream.

**Comment by ketzacoatl** [comment]
With a few updates, this is closer to being resolved:

```
Skipping Git submodules setup
$ scripts/ci/tfinit.sh
$ scripts/ci/tflint.sh
main.tf
	WARNING:348 Module source "../modules/init-snippet-gitlab-docker" is not pinned (terraform_module_pinned_source)

Result: 1 issues  (0 errors , 1 warnings , 0 notices)
ERROR: Job failed: exit code 1
```

ATM, the only lingering issue is due to the bug with upstream.

**Comment by ketzacoatl** [comment]
See the latest build at https://gitlab.fpcomplete.com/fpco-mirrors/terraform-aws-foundation/builds/5393.

**Comment by ketzacoatl** [comment]
`tflint` 0.6.0 includes a fix for the issue that blocks this from being resolved, and we've got an updated build image to test here.
