### ISSUE TITLE
Undeclared types on module variables

### ISSUE THREAD

**Issue by kerscher** [fpco/terraform-aws-foundation#108]
Types for variables on our modules are only being explicitly set when they consist of `list` or `map`. This prevents automated generation of a test suite with all modules (#105), as well as the problems listed on #103, repeated below. There are too many undeclared variables, so I have copied them into a [gist](https://gist.github.com/kerscher/eb7c36dc583fac7e7b763819d272395d). The following is an example of a valid snippet that would _not_ trigger a build error:

```
variable "foo" {
  type        = "string"
  description = "bar"
  default     = "baz"
}
```

Omitting `type = "string"` is a test error. This guarantees that type errors are identical at every call site, as undeclared types will only be resolved at the callee, leading to potentially two modules resolving to different types. This also means that even though `default = []` will infer `type = "list"`, without adding it you will only find breakage if changing to another type once you use the changed variable at the call site.

**Comment by ketzacoatl** [comment]
I agree this is something we should do and be more consistent about when accepting PRs for new modules. I'll add a note about this in the WIP CONTRIBUTING.md doc I have.

**Comment by ketzacoatl** [comment]
about 1/3 or 1/2 of the way there..

**Comment by ketzacoatl** [comment]
This is resolved. All modules have been updated, but I'm unable to run `undeclared-variables`, so I'm going to close this and move on. We can reopen or open a new issue in the future if needed.
