### ISSUE TITLE
A Pull-request template

### ISSUE THREAD

**Issue by NorfairKing** [fpco/terraform-aws-foundation#117]
@kerscher @ketzacoatl 

Here is a starting point;

For new modules/examples or changes
- [ ] Update the [changelog](https://github.com/fpco/terraform-aws-foundation/blob/master/CHANGELOG.md)
- [ ] Make sure that the module is documented
- [ ] Make sure that the module is added to `tests/main.tf`
- [ ] Make sure that the linting passes on CI
- [ ] Make sure that there is a playbook, and that it is up to date
- [ ] Make sure that there is a manual CI trigger that can test the deployment

**Comment by ketzacoatl** [comment]
@NorfairKing can you clarify what you mean by "playbook", that is not clear in this context.

Also note that much of this info would need to be added to our `CONTRIBUTING.md` doc.

**Comment by NorfairKing** [comment]
A playbook is an idiot-proof guide to follow to do something. In this case that would be a deployment.
A playbook is a way to prevent improvisation and panic when in a disaster situation, but it's a great way to make sure a certain problem is well-understood before a solution is run as well.

**Comment by ketzacoatl** [comment]
That is definitely a requirement for `examples` (which are technically modules, but have other wrappers, like a `Makefile` we've written to simplify / clarify the playbook).

On the other hand, the straight up `modules` would need example code for how to use the module, or similar.

Both `examples` and `modules` should have a README that includes a list of specific information. I think we should review https://github.com/hashicorp/terraform-aws-vault/blob/master/README.md and similar examples to identify the content we want to see in that README, and then provide a template for that README as well.

**Comment by ketzacoatl** [comment]
I've created a separate issue for that topic on the README. This template for PRs could reference that README template to communicate the expectations for documentation.

**Comment by ketzacoatl** [comment]
We should also update the changelog - https://github.com/fpco/terraform-aws-foundation/blob/master/CHANGELOG.md - I've added a note about this to the ticket description.

**Comment by kerscher** [comment]
There is one step missing for modules:
- [ ] Make sure module is included in `tests/main.tf`

**Comment by ketzacoatl** [comment]
@NorfairKing, @lpaulmp, or @mcgirr, would you be able to assist with this?

**Comment by mcgirr** [comment]
@ketzacoatl Sure! Is this something that would be suitable to put in the [contributing](https://github.com/fpco/terraform-aws-foundation/blob/master/CONTRIBUTING.md) file for the repo?

**Comment by mcgirr** [comment]
I've opened https://github.com/fpco/terraform-aws-foundation/pull/201 to address this.
