### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by lehins** [fpco/terraform-aws-foundation#13]
Some of terraform modules use 2 space indentation, others use 4 space indent. Agreement on consistent indentation is very important when many people maintain the same code base. My emac's dafault indent for `terraform-mode` was 2 spaces, plus I used `kubernetes` module as a model, which also had 2 space indent. Haskell indent poll made by Chris revealed a 2 space indent preference, and since that it is preference from Haskell community, I think, it is relevant for us here as well.

Any opposition to switching to 2 space indent in all modules?

**Comment by ketzacoatl** [comment]
@lehins, Personally, I would be in support of using `terraform fmt`, and that defaults to 2 space tabs.  We would need to run that on every module to reset to a common base everywhere. I think it would be good to do.

**Comment by ketzacoatl** [comment]
Having used `terraform fmt` a little, I'm not sure we want to use it (though it's worth considering). That question could be evaluated separately from the indentation issue here. `tf fmt` does a couple of weird things, one is adding blank lines between lines that use maps and lists, another is that it doesn't really indent multi-line lists enough.

**Comment by kerscher** [comment]
I vote for `terraform fmt` the entire thing, even with its weirdness. There are workarounds for some things it does strangely, such as separating blocks when there are comments in the middle. I can create a new branch and execute everywhere, creating one commit for module formatted. We can then review where it would be undesired with actual examples.

**Comment by ketzacoatl** [comment]
there are a couple of modules remaining, where I _really_ didn't like how `tf fmt` wanted to move a comment or some crap like that.. but this is complete otherwise.

**Comment by ketzacoatl** [comment]
I believe this is complete enough to close, we'll hit up new places with new commits/PRs/etc.
