### ISSUE TITLE
BIND module fails for empty `db_records_folder` parameter

### ISSUE THREAD

**Issue by kerscher** [fpco/terraform-aws-foundation#135]
# Expected behaviour

1. User instantiates `bind-server` and provides empty `db_records_folder`
1. The internal `null_resource` detects the empty parameter and skips copying any folder

# Actual behaviour

1. `"${var.db_records_folder}/"` is interpolated into `/`
1. Calling user sends `/` to `/tmp/db_records`
1. Permission failure to access all files under `/` fails the provisioner
1. Local `/` files are available on the instance
1. `terraform apply` fails

## Proposed solution

Send a dummy folder that gets removed upon `remote_exec`.

**Comment by ketzacoatl** [comment]
I believe these changes have been merged, though we haven't seen them run recently. I am going to close the issue as complete and open new tickets in the future if there are still issues here.
