### ISSUE TITLE
setup CI to run tests on S3 full access policy module

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/terraform-aws-foundation#144]
With #122 we have implemented tests on one of our S3 modules. The purpose of this issue is to get those tests hooked up to CI. This requires:

* updating `.gitlab-ci.yml`
* define the `stages`, with linting being the first, and deploying stuff to aws second
* define a job in the aws stage that has a manual trigger - it does not run on its own when a new build is run on gitlab.. an operator would need to use the gitlab UI to trigger the job to run. I think this is `when`
* use credentials stored in gitlab secrets for now, we'll probably use vault in the future

**Comment by mcgirr** [comment]
I'm currently working on this under the [ci-s3-full-access-policy-module](https://github.com/fpco/terraform-aws-foundation/tree/ci-s3-full-access-policy-module) branch. 

The current CI output (still a WIP) is available on the gitlab mirror [pipeline](https://gitlab.fpcomplete.com/fpco-mirrors/terraform-aws-foundation/pipelines) for that branch.

**Comment by mcgirr** [comment]
Closing this issue since it sounds like plan is to eventually shift all the CI for the repo to a Github Workflow as part of changes like https://github.com/fpco/terraform-aws-foundation/pull/320
