### ISSUE TITLE
`kube-stack-private` GovCloud example

### ISSUE THREAD

**Issue by kerscher** [fpco/terraform-aws-foundation#153]
## Requirements

- update the existing `kube-stack-private` example
- `kube-stack-private` _should_ support deploying to GovCloud, use a variable to specify one or the other
- may need to update the `kube-stack` module for all of this to work
- run dev on a separate branch until we're happy to merge to master, retain one example env, and support both the corporate and GovCloud partitions in the one example.

**Comment by ketzacoatl** [comment]
I've updated the description and dropped the "new example" label to clarify this should be an update to the existing example.

**Comment by ketzacoatl** [comment]
There is a data source for the partition, so I believe we can close this ticket in favor of #158, which ought to resolve this issue as well.
