### ISSUE TITLE
elk-stack module Not Deployable

### ISSUE THREAD

**Issue by giancarlocosta** [fpco/terraform-aws-foundation#161]
elasticsearch_internal_alb variable in elk-stack module has two types, 'map' and 'string'. Based on the elasticsearch module I'm pretty sure it should be just map. This is preventing ability to deploy elk-stack.

**Comment by ketzacoatl** [comment]
@giancarlocosta can you link to where in the code you are seeing this? Thanks!

**Comment by giancarlocosta** [comment]
@ketzacoatl https://github.com/fpco/terraform-aws-foundation/blob/master/modules/elk-stack/variables.tf#L117
