### ISSUE TITLE
elk-stack module not working with various versions of terraform

### ISSUE THREAD

**Issue by giancarlocosta** [fpco/terraform-aws-foundation#163]
When trying to deploy elk-stack module with terraform version 0.9.11 and 0.11.7, I get the following errors. (Below example is with 0.9.11 but I get similar for 0.11.7)

terraform0.9.11 plan -out plan.out
10 error(s) occurred:

* module.elk.module.elasticsearch.data.aws_iam_policy_document.data-node-role: "statement": required field is not set
* module.elk.module.elasticsearch.data.aws_iam_policy_document.data-node-role: : invalid or unknown key: source_policy_json
* module.elk.module.elasticsearch.data.aws_iam_policy_document.ec2-discovery-policy: statement.0: invalid or unknown key: action
* module.elk.module.elasticsearch.data.aws_iam_policy_document.ec2-discovery-policy: statement.0: invalid or unknown key: resource
* module.elk.module.elasticsearch.data.aws_iam_policy_document.master-node-role: "statement": required field is not set
* module.elk.module.elasticsearch.data.aws_iam_policy_document.master-node-role: : invalid or unknown key: source_policy_json
* module.elk.module.elasticsearch.data.aws_iam_policy_document.source_policy: statement.0: invalid or unknown key: action
* module.elk.module.elasticsearch.data.aws_iam_policy_document.source_policy: statement.0: invalid or unknown key: principal
* module.elk.module.logstash-kibana.data.aws_iam_policy_document.logstash-role: statement.0: invalid or unknown key: action
* module.elk.module.logstash-kibana.data.aws_iam_policy_document.logstash-role: statement.0: invalid or unknown key: principal

**Comment by ketzacoatl** [comment]
Thanks for the report @giancarlocosta, we'll take a look to review and see if we can reproduce.

**Comment by ketzacoatl** [comment]
Unfortunately, we haven't been able to work on this. ATM the ELK modules have not been updated in a while and are probably not working with the latest Terraform. Feel free to update them if that is relevant to you.
