### ISSUE TITLE
aws iam policy 

### ISSUE THREAD

**Issue by ramesh44557** [fpco/terraform-aws-foundation#181]
hi, 
    requirement is i need to give policy to iam user that he has to access s3 fully only in mumbai

**Comment by ketzacoatl** [comment]
Hi @ramesh44557,

Thanks for stopping by and dropping us a line. You will need to be more specific, as I'm not sure what you are trying to do, what the problem is, or how I could help. Can you clarify your issue?

**Comment by ketzacoatl** [comment]
Without additional info, I'll need to close the ticket. Let us know if we can make an update that would improve your experience, thanks for your interest in the project!
