### ISSUE TITLE
Fix interpolation for template provider version 2.0.0

### ISSUE THREAD

**Issue by lpaulmp** [fpco/terraform-aws-foundation#185]
Fix interpolation for template version 2.0.0 according the last [changelog](https://github.com/terraform-providers/terraform-provider-template/blob/master/CHANGELOG.md#200-january-14-2019)

### Requirements 
- Fix the interpolation for modules that have the double dollar sign
- Pin version of template provider for those modules

**Comment by Magicloud** [comment]
Assign to myself. This is blocking some other modules from being verified.

**Comment by Magicloud** [comment]
What to do, since our template normally is shell-compatible script:
- all variables passed from terraform in form `${tf_var}`
- all variables assigned and used within the script in form `$${sh_var}`
- all command substitution in form `$(cmd)`

**Comment by Magicloud** [comment]
Branch template_fix.11 contains my modification. Working on validation.

**Comment by Magicloud** [comment]
@ketzacoatl for opinion.

**Comment by ketzacoatl** [comment]
I'd like to keep the updates to the nexus example separate from the updates for the template provider, but it otherwise LGTM!

**Comment by Magicloud** [comment]
@ketzacoatl Reverted change in nexus example.
