### ISSUE TITLE
new module: autoscaling-policy-metric-alarm-pair

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/terraform-aws-foundation#195]
#156 created a new example that demonstates how to use AWS autoscaling policies and metric alarms to scale an ASG up and down based on the average CPU and memory load across the cluster. That example is great, but did not get into making a module out of the key resources for dynamic, load-based, auto scaling.

## Requirements

The purpose of this ticket is to create a module that would be re-used several times in that example. EG, instead of the following:

```
resource "aws_autoscaling_policy" "mem_up" {
  name = "${var.name}-asg-policy-mem-up"
  autoscaling_group_name = "${module.web-asg.name}"
  adjustment_type     = "ChangeInCapacity"
  cooldown            = 300
  scaling_adjustment  = 3
  policy_type         = "SimpleScaling"
}

# Cloudwatch Monitor Memory Up
resource "aws_cloudwatch_metric_alarm" "web_mem_scale_up" {
  alarm_name = "${var.name}-mem-scale-up-alarm"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods = "3"
  metric_name = "MemoryUtilization"
  namespace = "AWS/EC2"
  period = "60"
  statistic = "Average"
  threshold = "60"
  dimensions {
    AutoScalingGroupName = "${module.web-asg.name}"
  }
  alarm_actions = ["${aws_autoscaling_policy.mem_up.arn}"]
}
```

We'd have something like:

```
module "auto-scale-mem-up" {
  source = "../../modules/autoscaling-policy-metric-alarm-pair"

  asg_name     = "${module.web-asg.name}"
  metric_name = "MemoryUtilization"
}
```

The module should parametize the details of those two resources by defining a bunch of variables w/ defaults. Require only the `asg_name` and `metric_name` parameters.

Lastly, update the example to use the new module. There should be 4 occurances of the module, one for each up/down on the cpu/memory metrics.

**Comment by Magicloud** [comment]
The change was done. But the testing described in readme, did not work straight. Working on that.

**Comment by Magicloud** [comment]
Found issue #222 and fixed.
