### ISSUE TITLE
Questions regarding dns-server module. 

### ISSUE THREAD

**Issue by spstratis** [fpco/terraform-aws-foundation#198]
Hi, I'm using the bind-server module to generate a pair of dns servers in my VPC (GovCloud specifically). I'm running into a problem but don't believe it's an actual issue with the module itself but mores so my understanding of how to use it.  

In the CLI logs the issue starts right around this point in the process
```
module.dns.aws_instance.bind[1] (remote-exec): Processing triggers for systemd (237-3ubuntu10.12) ...
module.dns.aws_instance.bind[0]: Provisioning with 'file'...
module.dns.aws_instance.bind[1]: Provisioning with 'file'...
module.dns.aws_instance.bind.0: Still creating... (1m0s elapsed)
```

The time elapsed gets to about 6mins and then finally fails with the following:
```
* module.dns.aws_instance.bind[1]: timeout - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* module.dns.aws_instance.bind[0]: timeout - last error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
My thought is that the error is happening when it's trying to access the resources when setting up the null_resource since it's able to connect to the resource during the main `resource "aws_instance" "bind" {...}` block in the module.

here is how I'm running the module. I'm pretty sure the way I'm referencing the db_records is incorrect but it's not clear to me (as a TF newbie) how I should be setting that up. Would referencing that incorrectly cause the problem I'm running into? Is there anything else that I'm missing here? Thanks for any help!
```
module "dns" {
  source = "../../modules/bind-server"

  names                  = ["preprod_gov_dns_1", "preprod_gov_dns_2"]
  ami                    = "ami-14bcd275"
  instance_type          = "t3.small"
  subnet_ids             = ["subnet-64315112", "subnet-fe95f79a"]
  private_ips            = ["192.168.12.4", "192.168.22.4"]
  security_group_ids     = ["sg-03afeb64"]
  key_name               = "fedramp-preprod-deployer"
  private_key            = "files/private_key.pem"
  named_conf_options     = "${file("${path.module}/files/dns/named.conf.options")}"
  db_records_folder      = "${path.module}/templates/db_records"
}
```

**Comment by ketzacoatl** [comment]
Hello @spstratis,

Thanks for reaching out. IIRC, the module provisions the EC2 instances over SSH, so when you run terraform plan/apply/etc, you'll need to have network access to those instances.

Why do you believe the way you are referencing the db records is incorrect? Have you reviewed the example in our repo?

**Comment by spstratis** [comment]
Thanks for the quick response @ketzacoatl .  You're correct in that it does connect over SSH, and the script successfully connects to the resource when it's building out the actual instance. I can confirm this because I can see the log statements from this part of the module running 

```
  provisioner "remote-exec" {
    connection {
      type        = "ssh"
      host        = "${self.private_ip}"
      user        = "ubuntu"
      agent       = false
      private_key = "${file("${var.private_key}")}"

      # bastion_host        = "${var.bastion_host}"
      # bastion_user        = "${var.bastion_user}"
      # bastion_private_key = "${var.bastion_private_key}"
    }

    inline = [
      "${var.distro == "ubuntu" ? "sudo apt-get update && sudo apt-get install -y bind9 dnsutils && sudo service bind9 start" : "sudo yum install -y bind && sudo service named start && sudo chkconfig named on"}",
    ]
  }
```
The issue seems to be occuring when it's trying to run the null_resource, which is where it's setting up the triggers...

```
resource "null_resource" "bind" {
  count = "${length(compact(var.private_ips))}"

  triggers {
    named_conf         = "${var.named_conf}"
    named_conf_options = "${var.named_conf_options}"
    named_conf_local   = "${var.named_conf_local}"
    log_files          = "${join("|", var.log_files)}"
    instance_id        = "${aws_instance.bind.*.id[count.index]}"
  }

  connection {
    type        = "ssh"
    host        = "${aws_instance.bind.private_ip[count.index]}"
    user        = "ubuntu"
    agent       = false
    private_key = "${file("${var.private_key}")}"

    # bastion_host        = "${var.bastion_host}"
    # bastion_user        = "${var.bastion_user}"
    # bastion_private_key = "${var.bastion_private_key}"
  }
# leaving out the rest of the resource ...
```

The reason I mentioned I think I'm referencing the db files incorrectly is because the variable description for `dns_records_folder` mentions `"Path to locally rendered directory of zone files." I'm just referencing a folder that contains a `db.mydomain.com` file, but I'm not "rendering" it any specific way, so just wasn't sure if I'm doing it wrong and maybe that's playing a role in my connection issue. 

I was also following some instructions from this [blog post](https://www.fpcomplete.com/blog/amazon-govcloud-has-no-route53-how-to-solve-this?success=true) but it's a few years old and seems to do things a bit differently since I'm guessing there have been a lot of changes since then.

**Comment by spstratis** [comment]
Sorry if there is an example of using the module, I haven't been able to find one when searching through the repo.

**Comment by ketzacoatl** [comment]
The examples I was referring to are in https://github.com/fpco/terraform-aws-foundation/tree/master/examples, but I don't see one for this module. While I've used the module in GovCloud a bunch, I didn't write the original module and I haven't needed to run updates to it in the last year or so. What version of Terraform are you using? It's possible that there are updates required for `0.12.x`, though I am not sure.

This is an extract from old module docs, and maybe it helps:

```
/**
 *## Simple DNS server(s) running bind9.
 *
 *Supports setting up multiple servers in different AZs using the same
 *configuration.
 *
 *Currently the intent is for setting up caching/forwarding
 *servers on private VPCs (as Route53 provides serving DNS zones well).
 *
 *The `null_resource` provisioner will upload new options
 *and reload the configuration whenever it changes.
 *
 *TODO: support uploading additional files, such as DNS zones
 *
 *### Example
 *
 *    module "dns" {
 *      source  = "../../vendor/fpco/terraform-aws/tf-modules/bind-server"
 *      name = "dns"
 *      ami = "ami-7c803d1c" #Ubuntu 16.04
 *      subnet_ids = "${module.vpc.private_subnets}"
 *      private_ips  = ["${var.private_dns_ips}"]
 *      security_group_ids = ["${aws_security_group.dns.id}"]
 *      key_name = "${aws_key_pair.admin.id}"
 *      named_conf_options = "${file("${path.module}/files/dns/named.conf.options")}"
 *    }
 *
 *And `files/dns/named.conf.options` would be something like this:
 *
 *    options {
 *      directory "/var/cache/bind";
 *      forward only;
 *      # This is the Amazon DNS server, which is always at the VPC's '+2' address
 *      forwarders {
 *        10.0.0.2;
 *      };
 *      dnssec-validation auto;
 *
 *      auth-nxdomain no;    # conform to RFC1035
 *      listen-on-v6 { any; };
 *
 *      allow-query { any; };
 *    };
 *    # This is a private zone served by Route 53 that uses the Amazon DNS server
 *    zone "route53.example.com." {
 *      type forward;
 *      forward only;
 *      forwarders { 10.0.0.2; };
 *    };
 *    # This is the corporate domain that forwards/caches the corporate DNS servers
 *    zone "example.com." {
 *      type forward;
 *      forwarders { 10.10.1.50; 10.10.1.51; };
 *    };
 */
```

I stopped using this module in part b/c I came up with another way to provide DNS through consul, and this BIND module is a little clunky for what I'm used to with Consul (it's great on its own, but I push the limit of what's possible, so Consul has been working better for me).

Let me know if you need assistance with any of this on GovCloud, we'd be happy to help.

**Comment by ketzacoatl** [comment]
@spstratis,

> The reason I mentioned I think I'm referencing the db files incorrectly is because the variable description for dns_records_folder mentions "Path to locally rendered directory of zone files." I'm just referencing a folder that contains a db.mydomain.com file, but I'm not "rendering" it any specific way, so just wasn't sure if I'm doing it wrong and maybe that's playing a role in my connection issue.

In the blog post, there is this section:

```
resource "template-dir" "db-records" {
 source_dir      = "${path.module}/data/dns/templates/db_records"
 destination_dir = "${path.module}/data/dns/rendered/db_records"
}
```
This is simply rendering a directory of templates and writing each out to a new directory with the rendered text.

Unless I'm mistaken, you would want to do something similar, or point the module at a directory with your files for the records.

But either way, I'm not sure how that addresses your problem as that appears to be either a network or SSH connection issue.

Which of the remote provisions steps in https://github.com/fpco/terraform-aws-foundation/blob/master/modules/bind-server/main.tf do you see as failing?

**Comment by ketzacoatl** [comment]
Feel free to re-open if you have more questions or we can assist.
