### ISSUE TITLE
new module: ami-centos

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/terraform-aws-foundation#218]
Similar to the existing `ami-ubuntu` module, we could use a `ami-centos` variant.

## Requirements

* Review source accounts, choose an upstream carefully (the Ubuntu variant uses Canonical).
* Parametize with focus on the OS release/version, keeping it simple.

**Comment by qrilka** [comment]
@Magicloud that's what I have used in my tests:
```

data "aws_ami" "centos7-ami" {
  most_recent = true
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
  name_regex = "^CentOS.Linux.7.*x86_64.*"
  owners = ["679593333241"]
}
```

**Comment by Magicloud** [comment]
@qrilka Thanks.

@ketzacoatl This may not be "even simpler". We have some hardcoded APT usage (150 by simple grep) since we were binding to Ubuntu. This may be a requirement needs to be clearified. Is this a sole module, or others using ami-ubuntu should adapt this?

**Comment by Magicloud** [comment]
Please checkout centos.11 branch for module and unit test. If "no" is the answer to above question, then I will refine it for pull-request.

**Comment by Magicloud** [comment]
By the way, pipeline fails due to iam-group module. Seems like it is using 0.12 syntax.

**Comment by ketzacoatl** [comment]
This was resolved in https://github.com/fpco/terraform-aws-foundation/pull/221. The v.12 modules have also been excluded from tests on `master`, where we're still using v0.11.x
