### ISSUE TITLE
s3-remote-state.principals should not have empty list as default.

### ISSUE THREAD

**Issue by Magicloud** [fpco/terraform-aws-foundation#286]
Default value means the caller can skip that variable, but skipping that value ends up invalid policy document passing to AWS and terraform stuck on creating the policy.

The default value should be gone to inform the caller that he must pass a value.

**Comment by mcgirr** [comment]
I have https://github.com/fpco/terraform-aws-foundation/pull/297 for this issue

**Comment by mcgirr** [comment]
This issue has been completed now with https://github.com/fpco/terraform-aws-foundation/pull/297
