### ISSUE TITLE
Add module: custom Kubernetes cluster

### ISSUE THREAD

**Issue by kerscher** [fpco/terraform-aws-foundation#37]
Module should contain as inputs at least:

1. Number and size of master nodes
1. Number and size of worker nodes
1. CIDR ranges for the network model
1. VPC to use

As outputs, it should provide at least:

1. IPs of nodes

The module should not create its own VPC, or assume it will have access to non-GovCloud available resources — i.e. NAT gateways etc for the VPC should be provided by other modules the user instantiates separately in his Terraform code.

**Comment by ketzacoatl** [comment]
I believe this module exists as the `kube-stack` - https://github.com/fpco/terraform-aws-foundation/tree/master/modules/kube-stack - feel free to re-open if this assessment is incorrect.
