### ISSUE TITLE
light refactor for EC2 instance profiles and IAM policies

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/terraform-aws-foundation#48]
For modules that use IAM profiles and are generally hooked up to EC2 instance profiles, our modules should:

* Assume the user would create an EC2 instance profile, a role for the instance, and some number of policy attachments.
* Provide the components to make that easy. For example, the `persistent-ebs` module create the profile for you and gives it an inconsistent name - modules should create resources with names and under the assumption the instance profile may get several different policies giving it permissions to different resources on AWS.
* export the right outputs so as to facilitate that assumption above

**Comment by ketzacoatl** [comment]
In reviewing with @Magicloud, we outlined the following changes as well:

1) we want the `persistent-ebs` module to create the IAM policy it needs (but not the other IAM resources, we need to move those)
2) we want a new module for the IAM instance profile (moved resources from `persistent-ebs` module), and made generic
3) we want to use that new module in the `single-node-asg` module, passing it the IAM policy from the `persistent-ebs` module

**Comment by Magicloud** [comment]
I have made the change but having a question. There are 3 attributes exported but not used any where, do we still need them?

- asg_iam_profile_arn
- asg_iam_role_arn
- asg_iam_role_name

**Comment by Magicloud** [comment]
After the PR, I think this is harder than expected.

Consider the case: the instance needs both attach_ebs and associate_eip permissions. They are defined in two modules using the module we make here, hence there are two profile ids. But aws_instance takes one.

I have not figured out a way to merge profiles or policy documents. So I think the abstract level might need to be lower, taking actions/resources that are list(string) and merge them, then create one and only document.

**Comment by Magicloud** [comment]
Quote from @ketzacoatl :
> so we would create the role, pass the ARN in as a variable to persistent-ebs, and the module would create init/volume and then a IAM policy and attach to the role ARN. another module like persistent-ip could do the same for EIP, and then the single-node-asg module would create the role and use both persistent-ebs and persistent-ip in the same way.
> the role/policy attachment resource would be in the persistent-* modules and the policy itself where each policy is focused on providing access to the related resource (EIP/EBS volume/etc)
