### ISSUE TITLE
add a top level `main.tf` for the repo

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/terraform-aws-foundation#50]
The `main.tf` is a requirement for auto-discovery with the TF registry. It could be empty and void, and the registry would not really care. However, it's also a great opportunity to package up a demo or provide some concept of a "default" env for the AWS module repo.

**Comment by ketzacoatl** [comment]
We still need to figure out what should be in the top-level `main.tf`. Should this be a minimal example of how to use one of the VPCs? I don't think it's sensible to keep it empty, but it's difficult to decide what should go in it.

**Comment by kerscher** [comment]
This is already done
