### ISSUE TITLE
all modules should add `description` to all `outputs`

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/terraform-aws-foundation#57]
we're still using the `// description` as used by `terraform-docs`, but TF core now has support for `description` in the `output` - see https://www.terraform.io/docs/configuration/outputs.html#description-1

**Comment by ketzacoatl** [comment]
@lpaulmp, This is another easy task that would show you around the modules, while also improving the auto-generated docs displayed on the upstream Terraform registry.

**Comment by lpaulmp** [comment]
@ketzacoatl I opened a PR to address this issue
