### ISSUE TITLE
separate vpn-gateway scripts and Dockerfile into their own repo

### ISSUE THREAD

**Issue by ketzacoatl** [fpco/terraform-aws-foundation#63]
The VPN helper utility code would be better in a separate repo, leaving only the TF modules in this repo.

**Comment by ketzacoatl** [comment]
I've created a new repo - https://github.com/fpco/openconnect-gateway - for this code to live in.

**Comment by AronT-TLV** [comment]
Do you want me to do this “formally” with a PR or just move and delete?

**Comment by ketzacoatl** [comment]
I don't see much help in a PR for this, though code review and checking over one another's work are norms we aim to follow. No need to retain the git history of the files moved.

**Comment by AronT-TLV** [comment]
This is basically done. Waiting for approval on moved files before deleting from this repository.

**Comment by ketzacoatl** [comment]
LGTM, ship it!
