### ISSUE TITLE
Re-add `init_snippet_run_consul_server`

### ISSUE THREAD

**Issue by kerscher** [fpco/terraform-aws-foundation#87]
The `init_snippet_run_consul_server` module is currently being used downstream.
We should re-add, document and provide in the next released version.

**Comment by kerscher** [comment]
Initial import on this [commit](https://github.com/fpco/terraform-aws-foundation/commit/921e781f7d77a8326d41dd672455d994faf31881). Needs to be documented before merging.

**Comment by ketzacoatl** [comment]
I could be wrong, but I'm not sure that this is necessary, as the module had been renamed ( https://github.com/fpco/terraform-aws-foundation/commit/453539cd52a139a25056e477de6702a036c2e446), and then I believe the only change was to separate "configuring consul" from "running consul" (https://github.com/fpco/terraform-aws-foundation/commit/f64820ac2eb4cdcd03ae3cd4cc2dd3a351c40a60) - eg there was the removal of this line: https://github.com/fpco/terraform-aws-foundation/blob/921e781f7d77a8326d41dd672455d994faf31881/modules/init-snippet-run-consul-server/snippet.tpl#L22

..and that should be easy to integrate into the user's init code.

More info on the history for this module can be seen in https://github.com/fpco/terraform-aws-foundation/search?q=init-snippet-run-consul&type=Commits.

**Comment by kerscher** [comment]
You are right. We should document those changes somehow, though I’m not sure how. Does `terraform` exposes a deprecation mechanism for modules?

**Comment by ketzacoatl** [comment]
we're due for a changelog..
